# Description: Base functions for DevSpace
#
# Functions:
#   - require_vars: Require variables to be set
#   - require_flags: Require a pipeline flag to be set
#   - require_cmds: Require commands to be installed
#   - get_pod_by_label: Output the pod name or return error
#
version: v2beta1
name: devspace

functions:
  #
  # Require variables to be set
  #
  # Parameters
  # ----------
  # $REQUIRE_VARS
  #   (string) Array of variables to check
  #
  require_vars: |-
    REQUIRE_VARS=("${@}")
    for REQUIRE_VAR in ${REQUIRE_VARS[@]}; do
      if [ -z "${!REQUIRE_VAR}" ]; then
        echo "Error! \$$REQUIRE_VAR is not set. Exiting..."
        exit 1
      fi
    done

  #
  # Require a pipeline flag to be set
  #
  # Parameters
  # ----------
  # $FLAGS
  #   (string) Flags to check
  #
  require_flags: |-
    REQUIRE_FLAGS=("${@}")
    for REQUIRE_FLAG in ${REQUIRE_FLAGS[@]}; do
      if [ -z "$(get_flag "$REQUIRE_FLAG")" ]; then
        echo "Error! Flag --${REQUIRE_FLAG} is not set. Exiting..."
        exit 1
      fi
    done

  #
  # Require commands to be installed
  #
  # Parameters
  # ----------
  # $REQUIRE_CMDS
  #   (string) Array of commands to check
  #
  require_cmds: |-
    for cmd in "$@"; do
      if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Error! Required command '$cmd' not found."
        exit 1
      fi
    done
  #
  # Output the pod name or return error
  #
  # Parameters
  # ----------
  # $LABEL
  #   (string) Name of the label, e.g. app.kubernetes.io/component=wordpress
  # $NAMESPACE
  #   (string) Namespace to search in
  # $TIMEOUT
  #   (int) (Optional) Timeout in seconds
  #   Default value: 0
  #
  get_pod_by_label: |-
    # Args
    NAMESPACE="${1:-default}"
    LABEL="$2" && require_vars LABEL
    TIMEOUT=${3:-0}

    # Get the pod name
    START_TIME=$(date +%s)
    while true; do
      # Retrieve a pod (limit 1) by name, excluding Terminating pods
      POD_NAME=$(kubectl get pod --namespace=$NAMESPACE --selector $LABEL --no-headers 2>/dev/null | awk '$3 != "Terminating" {print $1}' | head -n 1)
      if [ -n "$POD_NAME" ]; then
        echo "$POD_NAME"
        break
      fi
      # Take pauses until timeout
      sleep 1
      NOW=$(date +%s)
      if [ $(($NOW - $START_TIME)) -gt $TIMEOUT ]; then
        exit 1
      fi
    done

vars:
  DEVSPACE_ENV_FILE: ".env"
  # Get project root directory, Windows compatible
  PROJECT_ROOT_DIR:
    command: pwd
    commands:
      - os: windows
        command: wsl --exec pwd
