# Description: Image related pipelines
#
# Commands:
#   - image-update-labels: Update the labels of the base image in the Dockerfile
#
version: v2beta1
name: devspace

imports:
  - path: base.yaml

pipelines:
  image-update-labels:
    flags:
      - name: dockerfile
        description: Fill path to the Dockerfile, relative to project dir. A .labels file will be created in the same directory as the Dockerfile.
        type: string
      - name: image-ref-label
        description: "The name of the image label to use as a version reference point."
        type: string
        default: "org.opencontainers.image.ref.name"
      - name: log-commit-messages
        description: "Output directory for the git commit logs. If set, creates a file with commit message and all changed assets."
        type: string
    run: |-
      # Requirements
      require_cmds skopeo jq

      # Get flags
      DOCKERFILE="$(get_flag dockerfile)"
      IMAGE_REF_LABEL="$(get_flag image-ref-label)"
      LOG_COMMIT_MESSAGES="$(get_flag log-commit-messages)"

      # Require vars
      require_vars DOCKERFILE

      # Validate
      if [ ! -f "$DOCKERFILE" ]; then
        echo "Dockerfile not found in $DOCKERFILE"
        exit 1
      fi

      # Extract the base image name from dockerfile
      BASE_IMAGE=$(grep '^FROM' "$DOCKERFILE" | head -n1 | awk '{print $2}' | cut -d' ' -f1)
      if [ -z "$BASE_IMAGE" ]; then
        echo "Can not find the base image in $DOCKERFILE"
        exit 1
      fi

      # Define variables
      LABELS_FILE="$(dirname $DOCKERFILE)/.labels"
      NEW_LABELS_FILE="$(mktemp)"
      IMAGE_NAME=$(basename $(dirname $DOCKERFILE))

      # Get the latest image labels
      echo "Fetching latest labels from $BASE_IMAGE"
      LATEST_IMAGE_LABELS="$(skopeo inspect docker://$BASE_IMAGE| jq -r '.Labels | to_entries | map(.key + ": " + .value) | .[]')"
      echo "$LATEST_IMAGE_LABELS" > "$NEW_LABELS_FILE"

      echo "Comparing the latest labels with the currently used labels in $LABELS_FILE"

      # Show current labels
      echo "Current labels:"
      if [ ! -f "$LABELS_FILE" ]; then
        echo "No labels file found."
      else
        cat $LABELS_FILE
      fi

      if [ ! -f $LABELS_FILE ] || [ "$(cat "$LABELS_FILE")" != "$(cat "$NEW_LABELS_FILE")" ]; then
        # Get old and new base image references
        BASE_IMAGE_REF="$(grep -oP "$IMAGE_REF_LABEL: \K.*" "${LABELS_FILE}" || true)"
        if [ -z "$BASE_IMAGE_REF" ]; then
          echo
          echo "Unable to find $IMAGE_REF_LABEL label and its value in the original ${LABELS_FILE}"
          echo "Contents of the original ${LABELS_FILE}:"
          cat "${LABELS_FILE}"
          exit 1
        fi
        
        NEW_BASE_IMAGE_REF="$(grep -oP "$IMAGE_REF_LABEL: \K.*" "${NEW_LABELS_FILE}")"
        if [ -z "$NEW_BASE_IMAGE_REF" ]; then
          echo
          echo "Unable to find $IMAGE_REF_LABEL label and its value in the new image labels"
          echo "Contents of the new image labels:"
          cat "${NEW_LABELS_FILE}"
          exit 1
        fi

        # Show latest labels
        echo "New labels:"
        cat "${NEW_LABELS_FILE}"

        # Update the .labels file
        echo "Updating the ${LABELS_FILE} to new labels."
        cat "$NEW_LABELS_FILE" > "$LABELS_FILE"

        # If LOG_COMMIT_MESSAGES is set, log the changes
        if [ -n "$LOG_COMMIT_MESSAGES" ]; then
            # Make sure the directory exists
            mkdir -p $LOG_COMMIT_MESSAGES

            # Log the changes
            LOG_FILE="$LOG_COMMIT_MESSAGES/$(date +%s)-labels.log"

            touch "$LOG_FILE"
            echo "Update $IMAGE_NAME labels from $BASE_IMAGE_REF to $NEW_BASE_IMAGE_REF" >> "$LOG_FILE"
            echo "$LABELS_FILE" >> "$LOG_FILE"
          fi

        echo "$LOG_COMMIT_MESSAGES updated."
      else
        echo "No changes to labels."
      fi
